name: Deploy to Koyeb

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: '${{ secrets.KOYEB_API_TOKEN }}'

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: eshop
          git-builder: docker
          git-docker-dockerfile: Dockerfile
          service-ports: "8080:http"
          instance-type: free
          skip-cache: true
